name: NoBedExplosions
version: @version@
main: xyz.tehbrian.nobedexplosions.NoBedExplosions
api-version: 1.16
authors: [ TehBrian ]
description: Fully control bed and respawn anchor functionality across all worlds, including allowing sleep in the nether or end!
website: https://www.spigotmc.org/resources/65808
commands:
  reloadnbe:
    description: Reloads the config of NoBedExplosions.
    permission: nobedexplosions.reload
    usage: /<command>
permissions:
  nobedexplosions.reload:
    description: Permission to use /reloadnbe.
    default: op
